In [5]:
import requests
import pandas as pd

url = "https://fakestoreapi.com/products"
data = requests.get(url).json()

df = pd.DataFrame(data)

# Clean & structure
df = df[["id", "title", "price", "category", "rating"]]
df["rating_rate"] = df["rating"].apply(lambda x: x["rate"])
df["rating_count"] = df["rating"].apply(lambda x: x["count"])
df.drop("rating", axis=1, inplace=True)

df.rename(columns={
    "title": "Product_Name",
    "price": "Price",
    "category": "Category"
}, inplace=True)


big_df = pd.concat([df]*50, ignore_index=True)


import numpy as np

big_df["Price"] = big_df["Price"] + np.random.randint(-10, 20, size=len(big_df))
big_df["rating_rate"] = big_df["rating_rate"] + np.random.uniform(-0.5, 0.5, size=len(big_df))


big_df["rating_rate"] = big_df["rating_rate"].clip(1, 5)


big_df.to_csv("ecommerce_big_data.csv", index=False)

print("✅ Final Data Shape:", big_df.shape)
big_df.head()

✅ Final Data Shape: (1000, 6)

,id,Product_Name,Price,Category,rating_rate,rating_count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",119.95,men's clothing,4.148469,120
1,2,Mens Casual Premium Slim Fit T-Shirts,27.30,men's clothing,3.714389,259
2,3,Mens Cotton Jacket,47.99,men's clothing,4.939648,500
3,4,Mens Casual Slim Fit,23.99,men's clothing,1.789160,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.748455,400

# cleaning dataset

In [2]:
# importing reguired libraries 
import pandas as pd


# Loading data
df = pd.read_csv("ecommerce_big_data.csv")
df

,id,Product_Name,Price,Category,rating_rate,rating_count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",119.95,men's clothing,4.148469,120
1,2,Mens Casual Premium Slim Fit T-Shirts,27.30,men's clothing,3.714389,259
2,3,Mens Cotton Jacket,47.99,men's clothing,4.939648,500
3,4,Mens Casual Slim Fit,23.99,men's clothing,1.789160,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.748455,400
...,...,...,...,...,...,...
995,16,Lock and Love Women's Removable Hooded Faux Le...,47.95,women's clothing,3.145830,340
996,17,Rain Jacket Women Windbreaker Striped Climbing...,29.99,women's clothing,3.917590,679
997,18,MBJ Women's Solid Short Sleeve Boat Neck V,16.85,women's clothing,4.518875,130
998,19,Opna Women's Short Sleeve Moisture,25.95,women's clothing,4.317382,146
999,20,DANVOUY Womens T Shirt Casual Cotton Short,19.99,women's clothing,3.263874,145

In [4]:
df.info()  # getting info about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1000 non-null   int64
 1   Product_Name  1000 non-null   object
 2   Price         1000 non-null   float64
 3   Category      1000 non-null   object
 4   rating_rate   1000 non-null   float64
 5   rating_count  1000 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 47.0+ KB

In [10]:
df.dropna(inplace=True) # Remove rows with missing values to keep the dataset clean
print(df)

     id                                       Product_Name   Price  \
0     1  Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...  119.95
1     2             Mens Casual Premium Slim Fit T-Shirts    27.30
2     3                                 Mens Cotton Jacket   47.99
3     4                               Mens Casual Slim Fit   23.99
4     5  John Hardy Women's Legends Naga Gold & Silver ...  695.00
..   ..                                                ...     ...
995  16  Lock and Love Women's Removable Hooded Faux Le...   47.95
996  17  Rain Jacket Women Windbreaker Striped Climbing...   29.99
997  18        MBJ Women's Solid Short Sleeve Boat Neck V    16.85
998  19                 Opna Women's Short Sleeve Moisture   25.95
999  20         DANVOUY Womens T Shirt Casual Cotton Short   19.99

             Category  rating_rate  rating_count
0      men's clothing     4.148469           120
1      men's clothing     3.714389           259
2      men's clothing     4.939648           500
3      men's clothing     1.789160           430
4            jewelery     4.748455           400
..                ...          ...           ...
995  women's clothing     3.145830           340
996  women's clothing     3.917590           679
997  women's clothing     4.518875           130
998  women's clothing     4.317382           146
999  women's clothing     3.263874           145

[1000 rows x 6 columns]

In [11]:
df.drop_duplicates(inplace=True)  #droping duplicates here

In [12]:
# Convert price column into numeric format for calculations
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["rating_rate"] = pd.to_numeric(df["rating_rate"], errors="coerce")
df["rating_count"] = pd.to_numeric(df["rating_count"], errors="coerce")

In [13]:
df = df[df["Price"] > 0]
df = df[df["rating_rate"] >= 1]
df = df[df["rating_rate"] <= 5]

In [14]:
df["Price_Category"] = pd.cut(
    df["Price"],
    bins=[0, 50, 150, 500, 1000],
    labels=["Low", "Medium", "High", "Premium"]
)

In [15]:


df["Popularity"] = pd.cut(
    df["rating_count"],
    bins=[0, 100, 300, 600, 1000],
    labels=["Low", "Medium", "High", "Very High"]
)

In [16]:
df["Product_Name"] = df["Product_Name"].str.strip()

In [17]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)

In [18]:
print(df.shape)
df.head()

(988, 8)

,id,Product_Name,Price,Category,rating_rate,rating_count,Price_Category,Popularity
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",119.95,men's clothing,4.148469,120,Medium,Medium
1,2,Mens Casual Premium Slim Fit T-Shirts,27.30,men's clothing,3.714389,259,Low,Medium
2,3,Mens Cotton Jacket,47.99,men's clothing,4.939648,500,Low,High
3,4,Mens Casual Slim Fit,23.99,men's clothing,1.789160,430,Low,High
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.748455,400,Premium,High